package sh;

import java.util.ArrayList;

import javax.jdo.PersistenceManager;

import com.google.appengine.api.datastore.DatastoreService;
import com.google.appengine.api.datastore.DatastoreServiceFactory;
import com.google.appengine.api.datastore.Entity;
import com.google.appengine.api.datastore.FetchOptions;

import jdodb.Item;
import jdodb.ListItem;
import jdodb.PMF;
import jdodb.ShoppingList;
import jdodb.Stock;
import jdodb.Store;
import jdodb.Template;
import jdodb.User;

import java.util.List;

import javax.jdo.Query;
import javax.servlet.http.HttpServlet;

public class LoadStartingData  extends HttpServlet {
	public static void loadData(){

		PersistenceManager pm = PMF.get().getPersistenceManager();
		try{
			Store s = new Store("Giant","5684 Corner Street",87987);
			Store s1 = new Store("Wegmans","9874 Stauten Avenue",98761);
			Store s2 = new Store("Bloom","9874 Bricks Street",98654);
			Store s4 = new Store("Macy's","3456 Stark Street",22569);
			pm.makePersistent(s);
			pm.makePersistent(s1);
			pm.makePersistent(s2);
			pm.makePersistent(s4);
			Template t = new Template("continental breakfast");
			Template t1 = new Template("thanksgiving dinner");
			Template t2 = new Template("back to school cloths");
			Template t3 = new Template("halloween party");
			pm.makePersistent(t);
			pm.makePersistent(t1);			
			pm.makePersistent(t2);
			pm.makePersistent(t3);
			User u = new User("Jack");
			User u1 = new User("Ian");
			pm.makePersistent(u);
			pm.makePersistent(u1);	
			Item i = new Item("Turkey",t1.getTypeID());
			Item i13 = new Item("Cranberry sauce",t1.getTypeID());
			Item i1 = new Item("Stuffing",t1.getTypeID());
			Item i2 = new Item("Party Mix",t3.getTypeID());
			Item i3 = new Item("Milk",t.getTypeID());
			Item i4 = new Item("Potatoes",t1.getTypeID());
			Item i5 = new Item("Soda",t3.getTypeID());
			Item i6 = new Item("Party Punch",t3.getTypeID());
			Item i7 = new Item("Shirt",t2.getTypeID());
			Item i8 = new Item("Pants",t2.getTypeID());
			Item i9 = new Item("Eggs",t.getTypeID());
			Item i10 = new Item("Potatoe Chips",t3.getTypeID());
			Item i11 = new Item("Ham",t1.getTypeID());
			Item i12 = new Item("Pumpkin pie",t1.getTypeID());
			Item pty1 = new Item("Confetti",t3.getTypeID());
			Item i14 = new Item("Corn",t1.getTypeID());
			Item cloth1 = new Item("Gloves",t2.getTypeID());
			Item cloth2 = new Item("Scarf",t2.getTypeID());
			Item i15 = new Item("English Muffin",t.getTypeID());
			Item i16 = new Item("Sausage",t.getTypeID());
			pm.makePersistent(i);
			pm.makePersistent(i1);			
			pm.makePersistent(i2);			
			pm.makePersistent(i3);			
			pm.makePersistent(i4);			
			pm.makePersistent(i5);			
			pm.makePersistent(i6);			
			pm.makePersistent(i7);			
			pm.makePersistent(i8);			
			pm.makePersistent(i9);
			pm.makePersistent(i10);
			pm.makePersistent(i11);
			pm.makePersistent(i12);
			pm.makePersistent(i13);
			pm.makePersistent(pty1);
			pm.makePersistent(i14);
			pm.makePersistent(i15);
			pm.makePersistent(i16);
			pm.makePersistent(cloth1);
			pm.makePersistent(cloth2);
			Stock as = new Stock(25,i.getItemID(),s2.getStoreID());
			Stock as1 = new Stock(30,i.getItemID(),s.getStoreID());
			Stock as2 = new Stock(40,i.getItemID(),s1.getStoreID());
			Stock as3 = new Stock(4,i13.getItemID(),s2.getStoreID());
			Stock as4 = new Stock(5,i13.getItemID(),s.getStoreID());
			Stock as5 = new Stock(6,i13.getItemID(),s1.getStoreID());
			Stock as6 = new Stock(5,i1.getItemID(),s2.getStoreID());
			Stock as7 = new Stock(9,i1.getItemID(),s1.getStoreID());
			Stock as8 = new Stock(7,i1.getItemID(),s.getStoreID());
			Stock as9 = new Stock(4,i2.getItemID(),s.getStoreID());
			Stock as10 = new Stock(5,i2.getItemID(),s1.getStoreID());
			Stock as11 = new Stock(4,i3.getItemID(),s1.getStoreID());
			Stock as12 = new Stock(3,i3.getItemID(),s2.getStoreID());
			Stock as13 = new Stock(2,i3.getItemID(),s.getStoreID());
			Stock as14 = new Stock(7,i4.getItemID(),s1.getStoreID());
			Stock as15 = new Stock(5,i4.getItemID(),s.getStoreID());
			Stock as16 = new Stock(4.5,i4.getItemID(),s2.getStoreID());
			Stock as17 = new Stock(5,i5.getItemID(),s.getStoreID());
			Stock as18 = new Stock(6,i5.getItemID(),s1.getStoreID());
			Stock as19 = new Stock(5,i5.getItemID(),s2.getStoreID());
			Stock as20= new Stock(5,i6.getItemID(),s.getStoreID());
			Stock as21 = new Stock(4,i6.getItemID(),s2.getStoreID());
			Stock as22 = new Stock(15,i7.getItemID(),s4.getStoreID());
			Stock as23 = new Stock(25,i8.getItemID(),s4.getStoreID());
			Stock as24 = new Stock(5,i9.getItemID(),s.getStoreID());
			Stock as25 = new Stock(6,i9.getItemID(),s1.getStoreID());
			Stock as26 = new Stock(4.5,i9.getItemID(),s2.getStoreID());
			Stock as27 = new Stock(5,i10.getItemID(),s.getStoreID());
			Stock as28 = new Stock(6,i10.getItemID(),s1.getStoreID());
			Stock as29 = new Stock(4,i10.getItemID(),s2.getStoreID());
			Stock as30 = new Stock(20,i11.getItemID(),s2.getStoreID());
			Stock as31 = new Stock(25,i11.getItemID(),s.getStoreID());
			Stock as32 = new Stock(27,i11.getItemID(),s1.getStoreID());
			Stock as33 = new Stock(10,i12.getItemID(),s.getStoreID());
			Stock as34 = new Stock(15,i12.getItemID(),s1.getStoreID());
			Stock as35 = new Stock(8,i12.getItemID(),s2.getStoreID());
			Stock as36 = new Stock(5,pty1.getItemID(),s.getStoreID());
			Stock as37 = new Stock(4,pty1.getItemID(),s2.getStoreID());
			Stock as38 = new Stock(10,i14.getItemID(),s.getStoreID());
			Stock as39 = new Stock(15,i14.getItemID(),s1.getStoreID());
			Stock as40 = new Stock(13,i14.getItemID(),s.getStoreID());
			Stock as41 = new Stock(15,cloth1.getItemID(),s4.getStoreID());
			Stock as42 = new Stock(17,cloth2.getItemID(),s4.getStoreID());
			Stock as43 = new Stock(4,i15.getItemID(),s2.getStoreID());
			Stock as44 = new Stock(5,i15.getItemID(),s.getStoreID());
			Stock as45 = new Stock(6,i15.getItemID(),s1.getStoreID());
			Stock as46 = new Stock(8,i16.getItemID(),s1.getStoreID());
			Stock as47 = new Stock(7,i16.getItemID(),s.getStoreID());
			Stock as48 = new Stock(6.5,i16.getItemID(),s2.getStoreID());
			pm.makePersistent(as);			
			pm.makePersistent(as1);			
			pm.makePersistent(as2);			
			pm.makePersistent(as3);			
			pm.makePersistent(as4);
			pm.makePersistent(as5);			
			pm.makePersistent(as6);
			pm.makePersistent(as7);
			pm.makePersistent(as8);
			pm.makePersistent(as9);
			pm.makePersistent(as10);
			pm.makePersistent(as11);
			pm.makePersistent(as12);
			pm.makePersistent(as13);
			pm.makePersistent(as14);
			pm.makePersistent(as15);
			pm.makePersistent(as16);
			pm.makePersistent(as17);
			pm.makePersistent(as18);
			pm.makePersistent(as19);
			pm.makePersistent(as20);
			pm.makePersistent(as21);
			pm.makePersistent(as22);
			pm.makePersistent(as22);
			pm.makePersistent(as23);
			pm.makePersistent(as24);
			pm.makePersistent(as25);
			pm.makePersistent(as26);
			pm.makePersistent(as27);
			pm.makePersistent(as28);
			pm.makePersistent(as29);
			pm.makePersistent(as30);
			pm.makePersistent(as31);
			pm.makePersistent(as32);
			pm.makePersistent(as33);
			pm.makePersistent(as34);
			pm.makePersistent(as35);
			pm.makePersistent(as36);
			pm.makePersistent(as37);
			pm.makePersistent(as38);
			pm.makePersistent(as39);
			pm.makePersistent(as40);
			pm.makePersistent(as41);
			pm.makePersistent(as42);
			pm.makePersistent(as43);
			pm.makePersistent(as44);
			pm.makePersistent(as45);
			pm.makePersistent(as46);
			pm.makePersistent(as47);
			pm.makePersistent(as48);
			
			ArrayList <ListItem> l1= new <ListItem>ArrayList();
			ListItem o1 = new ListItem(2,as.getCombineStoreAndItemID());
			ListItem o2 = new ListItem(2,as.getCombineStoreAndItemID());
			ListItem o3 = new ListItem(1,as6.getCombineStoreAndItemID());
			pm.makePersistent(o1);
			pm.makePersistent(o2);
			pm.makePersistent(o3);
			l1.add(o1);
			l1.add(o2);
			l1.add(o3);
			ShoppingList shpLst = new ShoppingList(15,15,u.getUserID(),l1);
			pm.makePersistent(shpLst);
		}finally{
			pm.close();
		}

	}

}
